name: GoMicroServices CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main and dev branches
  pull_request:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #to get a copy of the repository’s source code
      #Setup Go
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      #Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      #Build the application
      - name: Run build
        run: pwd

      #Run lint
      - name: Run lint
        run: make lint

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
